### ISSUE TITLE
Bookmark is created but include page anchor is not hyperlinked

### ISSUE THREAD

**Issue by limelime** [LarsGit223/dokuwiki-plugin-odt#106]
```
~~NOCACHE~~
====== Test anchor/bookmark with include page ======
  * Please refer to [[#IncludePageAnchor| Include page anchor]] section below.

{{page>IncludePageAnchor}}

```
After this, create IncludePageAnchor page with header=IncludePageAnchor.

**Comment by LarsGit223** [comment]
I had a look at the example. I did not use the include plugin before.

It seems like the anchor is not hyperlinked simply because it can not find the destination. Means a normal anchor/link will find a page or header it can point to. But in this case it looks like that the include plugin is transparent for the ODT export. Means to the ODT plugin it looks like the content of the included page belongs to the page. So, there is no destination to attach to.

I think here is possibly some interworking required between the two plugins. Therefore I rate this as an enhancement.

**Comment by LarsGit223** [comment]
Ok, forgot about the header. It's a bug of course.
