### ISSUE TITLE
Anchor from deeper include page doesn't work

### ISSUE THREAD

**Issue by limelime** [LarsGit223/dokuwiki-plugin-odt#114]
1)
Main page:
```
~~NOCACHE~~

====== Test anchor/bookmark ======
  * Please refer to [[#anchor| Anchor]] section below.
  * Please refer to **[[#anchor| Anchor]]** section below.

====== Anchor ======
Test anchor/bookmark.

{{page>deeperInclude}}


====== DeeperIncludePageAnchor ======
````
2)
`{{page>deeperInclude}}` page:
```
====== Test anchor/bookmark with DEEPER include page ======
  * Please refer to [[#DeeperIncludePageAnchor| Deeper include page anchor]] section below.
```

3) Export.
`deeperincludepageanchor` bookmark is created, but `Deeper include page anchor` link is wrong.

**Comment by LarsGit223** [comment]
This turned out to be caused in the plugin include itself, please have a look at https://github.com/dokufreaks/plugin-include/issues/182.

I therefore set this ticket to **wontfix** becaus the issue cannot be fixed by the ODT plugin. I will nevertheless keep it open until the issue in the include plugin is fixed.

**Comment by LarsGit223** [comment]
The pull-request/bugfix has been merged into the include plugin. So this can be closed.
