### ISSUE TITLE
Note number has bad formatting in the note

### ISSUE THREAD

**Issue by fpoto** [LarsGit223/dokuwiki-plugin-odt#167]
The text of footnotes immediately follows the note number, without any intervening space. Also, the note number has the same style as the text.

The note number should be in superscript mode and should be followed by a space (and possibly a right parenthesis).

**Comment by LarsGit223** [comment]
> The text of footnotes immediately follows the note number, without any intervening space.

If I write the following wiki code:
```
You can add footnotes((This is a footnote))by using double parentheses.
```
then the result in the browser and ODT seem to be the same regarding spaces. There is no space in the text but there is a space between the number and the text in the footnote at the bottom of the page. If I add some space like below:
```
You can add footnotes ((This is a footnote)) by using double parentheses.
```
then there is also a space in the text, in the browser and in the ODT document.
Maybe I oversee something but I do not know what you mean. Please explain.

> Also, the note number has the same style as the text.

> The note number should be in superscript mode and should be followed by a space (and possibly a right parenthesis).

I checked the ODT specification and this does not seem to be possible. The number and the text at the footer always seem to have the same style.

So for now I will mark this as an **enhancement** and also with **wontfix** as it currently seems not to be possible with ODT standard footnotes.

**Comment by fpoto** [comment]
Hmmm..  I can see the problem at home, but not at work, where I have a more recent version of Libreoffice. So the space problem I mentioned seems to be a Libreoffice problem, solved in the current version.

As for the superscript, that's a pity, it would be much better if the number were superscript, but we can live with it...

Thanks

**Comment by LarsGit223** [comment]
I did try again to get the different styles in the footnote footer text and got it working at least in LibreOffice.

I could give the footnote the wanted styles by doing the following:

1. Let's assume the footnote text is **ABCDEF**
2. Mark all the text in the footer and set the style to superscript
3. Now only mark the letters **BCDEF** and give them a normal text style (not superscripted)
4. Delete the **A**
5. Now the footnote number in the footer has superscript style but the text following it has a normal style

That means even in the LibreOffice GUI it was not very intuitive to do what we want but it seems possible. So I will remove the **wontfix** label now.

Anyway, I can not say when I will implement this.

**Comment by LarsGit223** [comment]
Just fixed this in the current master branch.
**Attention**: the master branch is not a release and there have been big changes in it. Of course you can try it out if you like.

Here is an example screenshot of how footnotes should look like now, after ODT export:

![footnoteexample](https://cloud.githubusercontent.com/assets/9009011/18417111/570f6fac-7827-11e6-87ca-f6c33dabcc14.png)

The numbering is different because the XHTML renderer does not handle duplicate footnotes correctly. But the ODT handling looks correct to me so I leave that as is.

The footnotes now have common styles assigned to it. That means the styles of the different "parts" of a footnote can now all be modified in the "Styles and Formatting" tool of LibreOffice. The following picture with modified styles illustrates which style belongs to which part:

![footnoteexported](https://cloud.githubusercontent.com/assets/9009011/18417068/7e5cbdb8-7826-11e6-8c7a-0cf87ab267c0.png)

**Orange** part: style **_Footnote Anchor_**, see _"Styles and Formatting / Character styles"_
**Blue** part: style **_Footnote Characters_**, see _"Styles and Formatting / Character styles"_
**Red** part: style **_Footnote_**, see _"Styles and Formatting / Paragraph styles"_
