### ISSUE TITLE
Affix wrap in plugin»odt»media_sel  & plugin»odt»usestyles

### ISSUE THREAD

**Issue by limelime** [LarsGit223/dokuwiki-plugin-odt#65]
If media_sel & usestyles are only used by Wrap plugin, then can you affix `wrap` to these options so that it is less confusing.
e.g.:
```
plugin»odt»wrap»media_sel
plugin»odt»wrap»usestyles
```

**Comment by LarsGit223** [comment]
I think you got me wrong.

Currently, it might be only wrap in which case it makes a diffeence to use media_sel and usestyles. But in the future it could have an effect on other plugins too.

Other installations might have specific CSS files and so use the options without my knowledge.

But the main point is that the number of plugins beeing affected by the options might change. So I think it is better to keep the names because that are not pure wrap specific options.

**Comment by LarsGit223** [comment]
Just to mention:
A re-design of the config option is on the roadmap, see issue #55. So maybe somethings will be changed in the future.

Thanks for letting me know that you find the options confusing, I will keep an eye on it.
